### ISSUE TITLE
Add inference benchmark suites

### ISSUE THREAD

**Issue by petermattson** [mlcommons/training_policies#1]
ML is not just training, we need inference too. Probably need to add two suites: Cloud Inference, Mobile/Edge Inference because benchmarks and metrics may differ. 

Supporting orgs:  Google, Intel, dividiti, Microsoft, Cisco, NVIDIA, Wave Computing, Alibaba, GM, SambaNova

**Comment by ddutta** [comment]
One proposal discussed on the mailer: leverage the training workloads to derive inference workloads.

**Comment by dskhudia** [comment]
Is results submission for inference performance included and if yes, any guidelines ?

**Comment by petermattson** [comment]
Not at present but we are working to develop the inference benchmarks.

**Comment by petermattson** [comment]
Kicked off inference effort! Closing.
