### ISSUE TITLE
update training rules for random seeds

### ISSUE THREAD

**Issue by christ1ne** [mlcommons/training_policies#105]
Hi,

[Special topics agenda ](https://docs.google.com/document/d/1BICAHzLKziO8hUaeLlc3U8AWW7_Tl9pmwWiwnaFwGO0/edit#) on Oct 3 agreed to use clock time to seed the random numbers. Please update the training rules to reflect that and remove the requirement on using seeds 1-5.

Thanks,
Christine

**Comment by petermattson** [comment]
Thanks, in process, closed as duplicate of #86. :-)
