### ISSUE TITLE
Scale up NCF

### ISSUE THREAD

**Issue by ableiweisss** [mlcommons/training_policies#113]
As we discussed in a previous MLPerf community meeting, the current NCF model is small. We have made some modifications to scale up both its embeddings and FC layers (see below). We propose to submit these changes in order to give this workload closer resemblance to real industry use cases. Should we submit changes for inference? training v1.0?

NeuMF(
  (mf_user_embed): Embedding(276986, 64)
  (mf_item_embed): Embedding(53488, 64)
  (mlp_user_embed): Embedding(276986, 256)
  (mlp_item_embed): Embedding(53488, 256)
  (mlp): ModuleList(
    (0): Linear(in_features=512, out_features=512, bias=True)
    (1): Linear(in_features=512, out_features=512, bias=True)
    (2): Linear(in_features=512, out_features=512, bias=True)
  )
  (final): Linear(in_features=576, out_features=1, bias=True)
)

**Comment by bitfort** [comment]
SWG:

For consideration after v0.5.0.

**Comment by petermattson** [comment]
Replaced with DLRM
