### ISSUE TITLE
Review Clock Starts

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#118]
Reference implementations have been adding the run_start tag. We should review the placement of this tag and reach consensus on it.

**Comment by bitfort** [comment]
SWG:

context/previous thoughts: generally, the clock starts right before the first random step of pre-processing and before the model is created ("We don't time one time data prep"). The clock starts have been moving over time to conform with this idea. This is in part motivated by the desire to reduce engineering effort for v0.5.*. In a distributed setting, the general expectation is that the system has started but has not seen the model yet. 

Next Step:

By Monday 9AM (Oct 22), all references should have clock start placed in the expected final location. Submitters WG will be asked over email to review and raise (and hopefully resolve) any questions/objections by Monday 5PM.

**Comment by petermattson** [comment]
When for distributed systems?
Horovod uses MPI init
Raw TF uses something else
Handshake vs graph construction
How are startup costs vs persistent timed

**Comment by bitfort** [comment]
SWG:

We recommend having a specific session in the next few days (schedule on the mailing list) to discuss clock starts.

**Comment by petermattson** [comment]
SWG (tentative, confirmed at next Special Topics / Weds noon).

The clock must start before any part of the system performs any benchmark specific work (e.g. model creation, or dataset manipulation), and may be stopped as soon as any part of the system determines target accuracy has been reached.
