### ISSUE TITLE
Random Seeding & RNG

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#120]
Clarify random seeding and RNGs.

**Comment by bitfort** [comment]
I have a few proposals to start with:

(A) No explicit seeding of RNGs are allowed for v0.5.0. RNGs should be seeded using their default seeding mechanisms. Currently in the rules you are only allowed to use "stock" RNGs. We believe "stock" RNGs have reasonable default seeding behavior. 

(B) Same as (A) but if an RNG is seeded, it must use the clock.

(C) You can seed using the clock or there are a white list of RNGs which can be left to use default seeding behavior (i.e. no explicit calls to seed).

**Comment by tremblerz** [comment]
If we implement (B) then there might be inconsistency in the convergence for the same workload ran in the same environment but at different times. What cases would not suffice with default seeding behavior?
Also, there are some issues around few workloads where the seeds are not passed to all submodules and those submodule resort to their default seeding behavior which can bring up inconsistency in the results.

**Comment by jbalma** [comment]
Why not just restrict to the list of seeds used in the reference runs? That gets around issues of convergence speed up due to lucky initialization from using system clock. Is there a good reason to allow for setting seeds to anything but the reference seeds?

**Comment by bitfort** [comment]
SWG:

You can use the following to seed RNGs:
- Clock
- Another RNG (initialized with an allowed seed)
- System source of randomness (e.g. /dev/random or /dev/urandom)

note 1: We also recognize that there are reasons to duplicate seeds in distributed environments
note 2: We recognize seeds are useful for reproducibility and stability, we feel this should be addressed intelligently in future submissions, possibly v1.0.0. For now random is rather random.

**Comment by amsaha** [comment]
I suggest we allow only two sets of experiments:

1. Random seeds from the default behavior of an RNG (from an approved list of RNGs) - _prevents choosing seeds that give better results_
2. Fixed set of seeds - _allows reproducibility_ 

If playing around with seeds is allowed, it can be abused to get favorable runs (assuming some seeds do indeed lead to faster convergence). 

I don't see the point of using the clock value or system source of randomness to seed RNGs.
