### ISSUE TITLE
SSD Samples

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#121]
https://github.com/mlperf/training/issues/166

**Comment by bitfort** [comment]
From previous issue:
Discuss the number of samples change to SSD reference. This was half the changes in PR144 (#144)

**Comment by bitfort** [comment]
SWG:

We would like some more data and ideally settle this through email on submitters; if not we may have an ad hoc meeting.

**Comment by robieta** [comment]
FYI: Here is how TensorFlow vectorizes the SSD crop proposal:

https://github.com/tensorflow/benchmarks/blob/2c34b38fb0272c51c8f60717f5aba6ddd5fdb837/scripts/tf_cnn_benchmarks/ssd_dataloader.py#L114

**Comment by petermattson** [comment]
SWG:
Any number >=1 is acceptable.
