### ISSUE TITLE
Update definition of reference result and benchmark result

### ISSUE THREAD

**Issue by TheKanter** [mlcommons/training_policies#124]
According to the rules:

> A reference result is the median of five run results provided by the MLPerf organization for each reference implementation
> 
> A benchmark result is the median of five run results normalized to the reference result for that benchmark. Normalization is of the form (reference result / benchmark result) such that a better benchmark result produces a higher number.
> 

I believe we have changed the definition of a result, so we should update these accordingly. I think we are using means and the # of run results varies by benchmark.

**Comment by petermattson** [comment]
Yes, will do.
