### ISSUE TITLE
Does the framework for benchmark has to be open sourced?

### ISSUE THREAD

**Issue by jackalcooper** [mlcommons/training_policies#125]
Quote:

> === Benchmark implementations must be shared
Source code used for the benchmark implementations must be open-sourced under a license that permits a commercial entity to freely use the implementation for benchmarking. The code must be available as long as the results are actively used.

Here it states that "Source code used for the benchmark implementations must be open-sourced". Does the implementation here means the source code for the network which usually is a graph representation or it includes the whole deep learning framework or library?

**Comment by bitfort** [comment]
SWG:

More precise rules on this will be drafted and will be circled on the mailing list.
