### ISSUE TITLE
Logging (L1 & L2)

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#126]
Seeking clarity on different logging levels, what is expected for submission, etc.

**Comment by christ1ne** [comment]
Is passing the mlp_compliance code checking mandatory? 
Is the logging having all exact tags mandatory?

**Comment by bitfort** [comment]
SWG:

L1 - basic checking including run_start and run_stop and evaluation.
L2 - L1 plus having at least one of every tag used by the reference. Values, number of tags, etc. not considered.
L3 - L2 plus extensive checking of values, formats such as learning rates being correct multiples of base step size. 

For v0.5.0, we will create an automatic checker. The checker will be posted for review by Friday (Oct 26). Will be open for review and hopefully finalized by EOD Tuesday 30th (pending major objections). Once finalized, this will be the checker used for submissions, independent of the state of the reference implementations. 

We will revisit this issue once finalized.

**Comment by petermattson** [comment]
SWG:
L2 for submission per auto checker.
For this submission, you can hand patch logs with proper annotations.

**Comment by qiuxin2012** [comment]
Do you have a script to check logs?

**Comment by petermattson** [comment]
https://github.com/mlperf/training/tree/master/compliance/mlperf_compliance

**Comment by petermattson** [comment]
Scripts exist. 
https://github.com/mlperf/training/tree/master/compliance/verify_submission
https://github.com/bitfort/mlp_compliance/blob/760559248fc61823488c606a0c507289752b88ba/mlp_compliance.py
Repurposing issue to track L3 compliance for 5.1.

**Comment by petermattson** [comment]
Obsolete.
