### ISSUE TITLE
Data shuffle

### ISSUE THREAD

**Issue by jackalcooper** [mlcommons/training_policies#127]
It could take a long time to do the data shuffle before each epoch. Should we substrate it from the benchmark result?

**Comment by bitfort** [comment]
SWG:

We recognize that shuffling can take a lot of time; we allow for optimizations such as shuffling shards. We unfortunately, we believe it is too close to the deadline to change wether shuffling is timed. We welcome discussion on shuffling and shuffling optimizations for future submissions.
