### ISSUE TITLE
epoch starts from 0

### ISSUE THREAD

**Issue by nvpstr** [mlcommons/training_policies#132]
It would be nice to have all reference implementation using the same starting value for **epoch**.
Currently ResNet, SSD and NCF are using 0.

**Comment by petermattson** [comment]
SWG:
Clarify in rules. First epoch is 0.

**Comment by christ1ne** [comment]
The latest logging spec asks for epoch starting from 1. Please ignore the last update. @petermattson please update the rule doc if needed.
