### ISSUE TITLE
MiniGo convergence & run requirement change

### ISSUE THREAD

**Issue by christ1ne** [mlcommons/training_policies#134]
Hello all, 

Please see below:

-------------------------------
We believe that convergence issue is from ‘bad initialization’. Our of 26 runs with just 1 epoch, there is 1 ‘bad initialization’.  We don’t have time to run more to get a more precise estimation.  We observed that a bad initialization is highly correlated to a bad convergence.   We define ‘bad initialization’  as in bootstrap selfplay stage, black wins <5% of games, or wins >95% of games.

How about we require 12 runs total and use first 10 converge, and define ‘non-converge’ as ‘Win Pct’ does not exceed threshold (0.55) for 10 epochs? 

-------------------------------
original issue:

We met an occasional situation that in first epoch, during 1v1 stage, the trained new model would always resign when its taking black, before take any move (num_move=0).  This makes convergence very very hard, new model always win 50% of the and get buried.   Then next epoch would start from the old model and train a new model again.   And the new model would also resign as soon as it take black.  And the whole thing repeats.  The symptom is we observe the new model kept being buried.   And when model resigns in the beginning of the game, there will be exception when dump the sgf file.

We tried to understand why this would happen.  So we look in to sgf file of the very first selfplay (bootstrap vs. bootstrap).   We find in a ‘bad’ start.  The selfplay games shows the white almost always win.  For example, in a bad start, during first round of selfplay.  White win 2031 games, and black only win 50 games.   In such situation, the agent would get a lot of experience when taking white, but very less experience when taking black.  So it will be very hard to win out and always get buried.  This make the training entering a ‘dead loop’, because the initial model is so biased, it is very hard for it to learn something useful.

We have some questions:

Is our understanding correct, that a highly biased bootstrap model would be a convergence problem?
Is it by design these highly biased init model would be generated from init process?
Is there something we can do with this situation?

**Comment by petermattson** [comment]
SWG:
Given probability, this should be handled by Olympic scoring. Could submit extra runs if extremely unlucky and support with data later. Also, can declare any run non-convergent at any time since it make score strictly worse.

**Comment by petermattson** [comment]
Appears resolved, at least until more data.
