### ISSUE TITLE
Object Detection: Treat FPN post-NMS-top-N as parameter scalable by batch size

### ISSUE THREAD

**Issue by slayton58** [mlcommons/training_policies#135]
The reference merges all proposed bounding boxes from all feature levels and images in the batch into a single tensor before applying a top-N. As the batch-size per GPU changes, the ratio of kept vs. discarded proposed boxes changes (Example: batch 2, 20k proposals over all feature maps and images, take 2k = 10% kept. Batch 1, 10k proposals over all feature maps, 2k kept = 20%. Similarly for b4 we'd keep 2k of 40k = 5%).

Changing this parameter to be a function of batch size per GPU would allow these ratios to remain constant.

Relevant code from the reference: https://github.com/ddkang/Detectron/blob/benchmarking/lib/ops/collect_and_distribute_fpn_rpn_proposals.py#L69-L86

I propose that we allow scaling this number of merged proposals taken by batch size (using 2000 proposals kept at batch 2 as the reference). Thus batch would keep 1k proposals, batch 4 would keep 4k)

**Comment by jackalcooper** [comment]
This has long been a confusing trick in detectron. In [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/rpn/inference.py#L159) they kept the same behavior. I think what you propose here requires a deep learning system has the capability to store and pass these RoIs between batches?

**Comment by petermattson** [comment]
Look at it offline.

**Comment by petermattson** [comment]
Duplicate.
