### ISSUE TITLE
 Does object detection task have to follow all the training rules?

### ISSUE THREAD

**Issue by jackalcooper** [mlcommons/training_policies#137]
1. Reference implementation downloads ResNet model from the internet. [config file](https://github.com/ddkang/Detectron/blob/master/configs/12_2017_baselines/e2e_mask_rcnn_R-50-FPN_1x.yaml#L33) . Is backbone's weight is an exception (in this case Res50)? If so it should be added to the rules.
2. the `run_and_time.sh` has `--box_min_ap 0.377 --mask_min_ap 0.339` but I can't find anything related to them. Training should be stopped when this two metrics are reached according to the training rules.

**Comment by petermattson** [comment]
SWG:
(1) Any pre-trained backbone of the correct model trained on the ImageNet image classification task is acceptable. Formalize in 5.1.
(2) Those parameters define the target accuracy, and must be checked at the same frequency as the reference implementation.

**Comment by jackalcooper** [comment]
```
RUN git clone https://github.com/ddkang/Detectron.git detectron
WORKDIR /packages/detectron
RUN git checkout benchmarking
```
In the [`Dockerfile`](https://github.com/mlperf/training/blob/master/object_detection/caffe2/Dockerfile) it is using a [fork](https://github.com/ddkang/Detectron.git) of Detectron. The branch is "benchmarking". Latest commit is fe3a7d1c2847ef631ae854eb729c0476e8ad1d5a, which is not what the submodule of training repo is tracking (80f329530843e66d07ca39e19901d5f3e5daf009).
You can easily see the difference between the two: [with target accuracy check](https://github.com/ddkang/Detectron/blob/benchmarking/tools/train_net.py#L179), [without target accuracy check](https://github.com/ddkang/Detectron/blob/80f329530843e66d07ca39e19901d5f3e5daf009/tools/train_net.py#L147)
This is quite confusing. Would be much better if it is updated.

**Comment by ddkang** [comment]
https://github.com/mlperf/training/pull/190

**Comment by petermattson** [comment]
Stopping criteria is fixed.
There is another issue for improving standard backbones.
