### ISSUE TITLE
Questions about flushing the cache before running the job

### ISSUE THREAD

**Issue by congxu-ml** [mlcommons/training_policies#142]
MLPerf requires to flush the cache before running the job. And following is the statement from mlperf website:
You must flush the cache or restart the system prior to benchmarking. Data can start on any durable storage system such as local disks and cloud storage systems. This explicitly excludes RAM. 

Can I flush cache with following command before each run without rebooting?
echo 1 > /proc/sys/vm/compact_memory; echo 3 > /proc/sys/vm/drop_caches

Thanks a lot!

**Comment by robieta** [comment]
Yes. That methodology was explicitly blessed when the rule was created.

**Comment by congxu-ml** [comment]
I see. Thanks!

**Comment by petermattson** [comment]
Appears resolved.
