### ISSUE TITLE
Mask R-CNN reference incorrectly runs for fixed number of epochs

### ISSUE THREAD

**Issue by petermattson** [mlcommons/training_policies#143]
Instead of eval every epoch and stop upon reaching target accuracy. We are assuming this is an error, and want to align with everyone else on this topic.

**Comment by nvpaulius** [comment]
I too would assume this is an error, a remnant from the early days of the benchmark code. @ddkang, are you "the owner" of mask r-cnn?

**Comment by ddkang** [comment]
It should run until it achieves the target accuracy. It currently stops at 10 epochs because it always hits accuracy around then.

In terms of evaluating every epoch, this PR does that (and updates logging): https://github.com/mlperf/training/pull/190

**Comment by petermattson** [comment]
Making this a training issue. "It currently stops at 10 epochs because it always hits accuracy **around then**." is not sufficient for a reference implementation.
