### ISSUE TITLE
List of inference issues

### ISSUE THREAD

**Issue by TheKanter** [mlcommons/training_policies#157]
Need to update the inference accuracy to reflect that we want to allow ~1-2% loss during deployment process.

**Comment by TheKanter** [comment]
Definition updates
Pre/post processing for open?
What hyperparameters do we want to have rules about (aside from batch size)?
Formal DUT/SUT definition
Input optimization - what input-based optimizations do we want to prohibit (e.g., quantization)
Single score for each set of BM results?

**Comment by petermattson** [comment]
Wrong place and obsolete.
