### ISSUE TITLE
Improving MLPerf Logging

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#160]
A few of the points of confusion around mentioned;
- Epoch numbering (start at 0 or 1)
- Reporting quality for maskrcnn which has 2 measures instead of 1
- Make a sepc for logging

Many others (feel free to add them as reply below)

**Comment by bitfort** [comment]
SWG Notes:

Request to involve inference working groups in logging; so inference can reuse or leverage the work.

**Comment by David-Levinthal** [comment]
array sizes and total number of tunable parameters
to establish at least a minimal model equivalence?

**Comment by bitfort** [comment]
SWG:

We have two parts to look at:
(1) Spec for the general tags (shared between benchmarks)
(2) Spec for benchmark specific tags

AI(NV&GOOG): pull engineering team for which benchmarks we think did it right (and why?).

**Comment by petermattson** [comment]
Closing as obsolete, logging has advanced substantially. Please open specific issues if required.
