### ISSUE TITLE
Getting CLA Signed

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#161]
How to get legal sign off for the CLA. Is there a better way to get this sign off? 

SWG Notes:

Is there any way we can lower the legal bar for submitting to the benchmark or give guidance, or means, or otherwise make it easier? Can we document this, walk through, etc.?

Can you have the physical document as a PDF?

**Comment by petermattson** [comment]
I believe we debugged this for Cray. Please contact info@mlperf if anyone else has additional qns.
