### ISSUE TITLE
Translation (Transformer & GNMT) Vocab Changes

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#162]
SWG Notes:

There is some confusion around the transformer vocab generation. This will be updated with more information from interested submitters/WGs.

No Concrete proposal -- waiting for mailing list or Special Topics to propose solution (from Nvidia?).

**Comment by bitfort** [comment]
SWG Notes:

NMT - No changes for v0.6 (re: vocab)
Transformer - change to load the vocab from file coming to the reference. Help make sure everyone is using the same vocab.

**Comment by petermattson** [comment]
Fixed by mlperf/training PR 244: transformer vocab
