### ISSUE TITLE
Making NCF Reflect Production Usage

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#163]
SWG Notes:

NCF does not reflect common loads people use in industry. There are multiple proposals to improve -- currently resolution is being pushed forward by Intel & Google.

**Comment by bitfort** [comment]
SWG Notes:

See MLPerf training repo PR #256 with new code update to NCF.

In brief, making the benchmark larger (dataset ~60x) and longer running.

**Comment by petermattson** [comment]
NCF replaced by DLRM.
