### ISSUE TITLE
Whitelist precisions

### ISSUE THREAD

**Issue by petermattson** [mlcommons/training_policies#17]
We would like to whitelist precisions known to work via discussion group. The whitelist should probably include FP16 (including IEEE and proprietary formats), FP32, and INT16. (From 5/17 meeting)

**Comment by dylanzika** [comment]
Will INT8 be considered in this list or future lists? This is especially for relevant to inference.

**Comment by petermattson** [comment]
From Greg Diamos:

 2) Precision whitelist for training (fp64, fp32, fp16 mul+fp32 accumulate, bfloat16 mul + fp32 accumulate (let me know if this isn't what the TPU does)).  I would be open to others if there is evidence that we could cite.

**Comment by bitfort** [comment]
The submitters working group consensus:

- The formats of fp64, fp32, fp16, and bfloat16 are pre-approved for use.
- Additional formats may be proposed to the submitters working group for pre-approval.
