### ISSUE TITLE
Update GNMT quality target (22 to 24)

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#174]
Previous agreement among submitters.

**Comment by bitfort** [comment]
SWG Notes:

We agree that we intend to move to 24 as a target. There is an AI to modify the reference and collect data on this.

**Comment by bitfort** [comment]
SWG Notes:

AI(NV) - Check target quality on english to german.
AI(Intel) - Check english to french. 
Related to:
https://github.com/mlperf/policies/issues/175

**Comment by bitfort** [comment]
SWG Notes:

(for english to german) Reference does not reach 24 at implemented, but does reach 24 with some changes: different weight initialization, different batching (matching Google's 0.5 submission), and something else. This convergence was confirmed at large batch sizes. 

Continuing AI for english to french. 
AI(Google) - Gather more opinions on german v. french, and dataset statistics (ratio of eval to train data).

**Comment by bitfort** [comment]
SWG Notes:

Presented findings for GNMT on French;
Approximately 38.9 max accuracy (BLEU, NV's v0.5 submission), 4400 s/epoch on 8xV100. Approximately 20 epochs to converge to max; 37-ish hits between 2 and 5. It appears to add overhead time in initial experiments (38s -> 213s).

**Comment by christ1ne** [comment]
What batch sizes have you tried in the existing master code and the new code in this PR? We are interested to see if the code converges at target accuracy 24 with batch size around 1k as an example.

**Comment by bitfort** [comment]
SWG Notes:

(We think it is likely to converge with at least 1k batch.)

We will change the quality target for gnmt to 24; pending the following AIs:

AI(Google) - Check convergence with larger batch (1, 2, 4k).

**Comment by bitfort** [comment]
SWG Notes:

We recognize that the quality target has been changed to 24 for GNMT for v0.6.
