### ISSUE TITLE
Baseline for references

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#176]
Originally we choose the baseline for benchmarks as "1 p100 week." How do we want to define our baseline runtimes for references?

**Comment by bitfort** [comment]
SWG Notes:

We agree this a large topic worth exploring. Additional considerations is how expensive the benchmark suite is to run (e.g. here is how many runs each benchmark needs).

**Comment by bitfort** [comment]
We feel this has a temporary solution for v0.6; we can re-open for the next submission.

**Comment by petermattson** [comment]
No action in rules
