### ISSUE TITLE
Allowing LARS as a Resnet Optimizer

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#177]
There was consensus among submitters in v0.5.0 that we want to enable LARS for resnet to enable scaling the benchmark on larger systems.

**Comment by bitfort** [comment]
SWG:

Generally agree that LARS should be allowed for resent assuming it converges. 

AI(Google) to show it converges. Specifically -- show there exists a resnet with LARS which hits accuracy 75.9 and provide parameters for people.

**Comment by bitfort** [comment]
SWG Notes:

Google shared code for this. 

There seems to be support for limiting LARS to large scales, such as 16k+ (exact number TBD).

AI(Google) -- File a PR, with a high level summary.

**Comment by bitfort** [comment]
SWG Notes:

We agree to allow LARS for 16k and higher for resnet (pending PR by google and review).

**Comment by petermattson** [comment]
No batch size limit, see SWG: in 196.

**Comment by petermattson** [comment]
Made active again, since this debate is ongoing.

**Comment by petermattson** [comment]
Duplicate of #346 (will be handled by the HP table merge)
