### ISSUE TITLE
Resnet Target Accuray 

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#179]
SWG Notes:
Confirm resnet reaches target accuracy (75.9). 

AI(Goog) - Verify the target accuracy.

**Comment by christ1ne** [comment]
The current code does not check for top-5 accuracy. Can I assume top-5 won't be checked going forward?

**Comment by petermattson** [comment]
SWG: agreed not to track top 5 at this time.

**Comment by bitfort** [comment]
SWG Notes:

Google confirms that large batch size of 32k is achievable with an internal implementation. Additional work and review is needed to confirm reference works.

**Comment by petermattson** [comment]
Used this accuracy successfully in v0.6, no further action required.
