### ISSUE TITLE
Freeze model list for v0.6

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#182]
SWG Notes:

We want to finalize the list of models by next Wednesday. We will follow up in special topics on Wednesday to confirm. Our belief is that we are not adding models. Please raise concerns over email prior to Wednesday next week. 

AI(Everyone): confirm this internally.

**Comment by bitfort** [comment]
SWG Notes:

Consensus for v0.6: 
GNMT
Transformer
Maskrcnn
SSD
Resnet
NCF (larger scale)
Minigo (new 19x19, new 9x9, or old TBD)

**Comment by christ1ne** [comment]
agree to the list of 7 models but agreed changes at each model need to be specified further.

**Comment by petermattson** [comment]
No further action required, closed.
