### ISSUE TITLE
Clarify language around "release"

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#189]
Clarify the language around software release used for submission.

**Comment by bitfort** [comment]
SWG Notes:

Proposal: all submissions are a mix of open source code as well as closed-sourced binaries. For binaries, we relax from official release to a "preview" or "beta" release under the assumption that optimizations will be included in a future "official" release. For open source software, you must base on any commit in an "official" repo plus a diff to support a particular architecture. 

We recognize this is a trade-off to reduce the burden of synchronizing releases with MLPerf.

AI(Everyone) -- discuss internally to see if (1) this would actually reduce effort and (2) be an acceptable solution.

**Comment by christ1ne** [comment]
I think it is better to ask for an PR for open source code instead of just an offline diff. The goal is to show the intent that code is ready for deployments.

**Comment by bitfort** [comment]
SWG Notes:

We should think about closed source software which is coupled with the hardware, only available if buying the hardware.  

We agree to write this into the v0.6 rules.

**Comment by svnoesis** [comment]
Is there an updated rules document for v0.6 with the above mentioned changes included ? Can you please point to the same ?

**Comment by rachithayp** [comment]
Is there a decision on whether for open source software, the diff needs to be in any specific format or should it be a PR?

**Comment by christ1ne** [comment]
@rachithayp a PR should be good enough per the MLPerf discussion last time but we should clarify in the rules. @petermattson

**Comment by nvpaulius** [comment]
Well, I'm not sure a PR for any ToT version of SW is quite acceptable for the production category. I think that category should require that any SW is officially endorsed by the vendor for use by its customers. For example, by appearing for download on the page as all the official releases even if it's a release candidate. And without any disclaimers that it's for benchmarking purposes only.

**Comment by petermattson** [comment]
Resolved in revised submission rules.
