### ISSUE TITLE
Timeline Update

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#190]
We are running short on time for the training benchmark. What are people's thoughts? It looks like we're about 2 weeks behind schedule.

**Comment by bitfort** [comment]
SWG Notes:

No objections noted for a 2 or 3 week pushback of training submission date. 

Pending any objections from the inference WG, we expect this to be finalized next week.

**Comment by bitfort** [comment]
SWG Notes:

Current target timeline:
- "Slush" Mar 29
- May 24 Submission
- Publication June 24

**Comment by bitfort** [comment]
SWG Notes:

We confirm:
May 24 Submission ** FINAL
Publication June 24 -- subject to results working group, tentative recommendation amend to 26th.

**Comment by petermattson** [comment]
No further action needed.
