### ISSUE TITLE
ToU update regarding comparisons with baseline

### ISSUE THREAD

**Issue by christ1ne** [mlcommons/training_policies#191]
The current ToU does not mention the guidelines when referring to MLPerf baseline. When comparing with baseline, we should clarify the needed text. Are the following text choices OK?
a. MLPerf baseline score with "name of reference HW"
b. MLPerf baseline score with unoptimized software on  "name of reference HW"
c. other choices

Please share your additional concerns.

Thanks,
Christine

**Comment by petermattson** [comment]
Baseline has been removed as a concept.
