### ISSUE TITLE
SWG Notes

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#192]
Participants Aril 1,

Cheng, Christine (Intel),
Victor Bittorf (Google),
Dehao Chen (Google),
Jacob Balma (Cray),
Peter Mattson (Google),
Mahathi Salopanthula (AMD),
Xinyuan Huang (Cisco),
Pankaj Kanwar (Google),
Paulius Micikevicius (NVIDIA),

**Comment by bitfort** [comment]
April 18, 2019

Cheng, Christine (Intel),
Keith Achorn (Intel),
Mahathi Salopanthula (AMD),
Uday Kurkure (VMWare),
Jonathan Choen (NVIDIA),
Shomy Sanyal (AMD),
Xinyuan Huang (Cisco),
Paulius Micikevicius (NVIDIA),
Vahid Sherkat (huawei),
David Kanter,

**Comment by bitfort** [comment]
April 25, 2019

Jonathan Choen (NVIDIA),
Paulius Micikevicius (NVIDIA),
Jacob Balma (Cray),
Mahathi Salopanthula (AMD),
Shomy Sanyal (AMD),
Dehao Chen (Google),
Peter Mattson (Google),
Frank Wei (Alibaba),
Tayo Oguntebi (Google),
Cheng, Christine (Intel),

**Comment by bitfort** [comment]
May 2nd, 2019

Victor Bittorf (Google)
Paulius Micikevicius (NVIDIA)
Peter Mattson (Google)
Jacob Balma (Cray)
Justin Sang (Huawei)
Cheng, Christine (Intel)
Shomy Sanyal (AMD)
Dehao Chen (Google)
Mahathi Salopanthula (AMD)
Frank Wei (Alibaba)
David Kanter (David Kanter)
Xinyuan Huang (Cisco)

**Comment by bitfort** [comment]
May 9th, 2019

Victor Bittorf (Google)
Francois Wellenreiter (ATOS)
Xiaoqi Cao
Justin Sang (Huawei)
Cheng, Christine (Intel)
Jonathan Choen (NVIDIA)
Shomy Sanyal (AMD)
Frank Wei (Alibaba)
Peter Mattson (Google)
Paulius Micikevicius (NVIDIA)

**Comment by bitfort** [comment]
May 23rd, 2019

Victor Bittorf (Google)
Wei Zhang
Masafumi Yamazaki
Shomy Sanyal (AMD)
Paulius Micikevicius (NVIDIA)
David Kanter (David Kanter)
A Ike
Peter Mattson (Google)
Naveen Kumar (Google)

**Comment by bitfort** [comment]
June 20th, 2019

Victor Bittorf (Google)
A Ike (Fujitsu)
Justin Sang (Huawei)
Cheng, Christine (Intel)
Cody Coleman (Stanford)
David Kanter (David Kanter)
Frank Wei (Alibaba)
Hayato Mwesigwa (Fujitsu)
Jonathan Choen (NVIDIA)
Paulius Micikevicius (NVIDIA)
Mahathi Salopanthula (AMD)
Dehao Chen (Google)
Peter Mattson (Google)
Xinyuan Huang (Cisco)
Masafumi Yamazaki (Fujitsu)

**Comment by bitfort** [comment]
July 25th,

Victor Bittorf (Google)
Hayato Mwesigwa (Fujitsu)
Shomy Sanyal (AMD)
Jonathan Choen (NVIDIA)
Mahathi Salopanthula (AMD)
A Ike (Fujitsu)
Frank Wei (Alibaba)
Cheng, Christine (Intel)
Jonathan Choen (NVIDIA)
Peter Mattson (Google)

**Comment by petermattson** [comment]
Obsolete practice.
