### ISSUE TITLE
Clarify Evaluation Frequency

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#193]
Discuss and clarify the resnet evaluation frequency.

**Comment by bitfort** [comment]
Specifically -- "at least" versus "exact" form frequency.

**Comment by bitfort** [comment]
SWG Notes:

For v0.6, there is a strong argument for "exactly the frequency of the reference" because it simplifies and reduces work. If we use the wording "at least," it allows for trade-offs (using resources for evaluation versus converging earlier). If we allowed "at least", we would probably have to allow borrowing, and also rule on sub-epoch evaluation. 

We also observe that some submissions in v0.5 did "exactly" and some did "at least" the prescribed evaluation frequency. Specifically, you follow the reference schedule either way -- in "at least" you can add additional evaluations. 

AI(submitters) -- Discuss internally if you would like "at least" or "exactly".

**Comment by bitfort** [comment]
SWG Notes:

Our thoughts is that it is pragmatic at this point in the benchmark to use the word "exactly." While there are merits to both approaches, "exactly" reduces the work submitters need to do -- specifically, submitters do not need to treat this as another "hyperparameter" and "tune" their evaluation strategy. But we will continue discussion here next week in consideration of everyone's thoughts and needs. 

We all agree that "sub epoch" evaluation is not desired for multiple reasons including: (1) it is difficult to define, (2) it requires significant engineering effort.

**Comment by bitfort** [comment]
SWG Notes:

For v0.6 we agreed to go with "exactly" as many evaluations as the reference.

**Comment by frank-wei** [comment]
Submitted a PR #223

**Comment by petermattson** [comment]
Table updated by PR #339
