### ISSUE TITLE
Submit results with own framework

### ISSUE THREAD

**Issue by frank-wei** [mlcommons/training_policies#194]
Related with #189 
Just confirm we can submit results using own framework written with C++ other than TF or pytorch. 
Should we open source or closed source? What is the criterion?

**Comment by bitfort** [comment]
SWG Notes:

A few thoughts:
* It is required to be open source. 
* The requirements varies depending on if the submission is in open or closed (and if closed, which part of closed, e.g. research?). Submitting to open is much easier.
* We encourage all submissions and would like to work with you to make this submission work. 

Feel free to reach out with more information.

**Comment by bitfort** [comment]
Additional notes:

- It must meet one of the available/preview/research requirements
- Must show optimizer equivalence.
- A reasonable engineer must be able to determine model equivalence in a reasonable amount of time (i.e. not black box, too complicated to understand)
