### ISSUE TITLE
NCF for v0.6

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#195]
SWG Notes:

Summary of technical discussion:
- Previous issues: overfitting, issues at epoch boundary
- Technical progress has been made on both and improvements have been shown in the reference
- Proposed accuracy target 0.51 (expected 4-6 epochs on reference)
- There is a candidate reference implementation which can be frozen
- The candidate is in a branch called "alias".

We note that the deadline is nearing and we do not have much time to iterate on this. 

Options to consider:
- No NCF submission.
- NCF submission with no change to deadline (may be hard to submitters).
- NCF submission with deadline push.

We would like an off-cycle submitters Monday for final decision. 
AI(submitters): Go through options internally, and if willing to push deadline, have sense for that timeline.

**Comment by bitfort** [comment]
SWG Notes:

Our decision is no NCF submission for v0.6. It may still appear in some way in the results table (perhaps blacked out or "under construction"). 

We intend to have NCF v2 in the next submission round, possibly even as a v0.6.1 submission before v0.7.  We all clearly want to keep pushing forward on NCF.

**Comment by petermattson** [comment]
NCF dropped from suite.
