### ISSUE TITLE
Training v0.6 guideline and codes

### ISSUE THREAD

**Issue by xqcao0559** [mlcommons/training_policies#197]
The submission deadline of training v0.6 is approaching. 

However, there seems no official guideline (documentations) for v0.6 accessible to the public (I looked all over github-mlperf but without any clue about training v0.6, or I ) and also the training code also matches training v0.5 (e.g. https://github.com/mlperf/training/blob/master/compliance/mlperf_compliance/mlperf_log.py) 
If these materials can be updated for v0.6, the preparation of submitters can be easier.

**Comment by TheKanter** [comment]
Victor, who chairs the submitters group, can help get you up to speed!

But the right way to start is by attending submitter's group meetings,
which are Thursdays at 11am pacific time.

David

**Comment by bitfort** [comment]
Yes -- we are working on new material for v0.6 -- it is taking a while to finalize. The best way to prepare for this round is to attend the submitters working group. Please reach out on the forum https://groups.google.com/forum/#!forum/mlperf and I can send you an invite to the working group and additional information. 

Victor

**Comment by xqcao0559** [comment]
Thanks, Victor.

There are two submitters groups for training:
Submitters WG and Training Submitters WG. Please add me in, and we could
find information for training v0.6. :)

Best,
Xiaoqi





Victor Bittorf <notifications@github.com>于2019年5月1日 周三00:57写道：

> Yes -- we are working on new material for v0.6 -- it is taking a while to
> finalize. The best way to prepare for this round is to attend the
> submitters working group. Please reach out on the forum i
> https://groups.google.com/forum/#!forum/mlperf and I can send you an
> invite to the working group and additional information.
>
Victor

**Comment by bitfort** [comment]
Which email should I invite?

**Comment by xqcao0559** [comment]
Actually, I have no idea which one of the two training submitters WG is
commonly used.
Please add xqcao0559@gmail.com to the both. Many thanks.

Victor Bittorf <notifications@github.com>于2019年5月3日 周五04:56写道：

**Comment by ff7250** [comment]
> Which email should I invite?

Pls kindly add xyliu.sh@gmail.com to the training submitters WG too. It's confusing now since the deadline is approaching.

**Comment by petermattson** [comment]
Rules are much more findable with website update.
