### ISSUE TITLE
Number of runs for Each Benchmark

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#199]
How many times should each benchmark be run?

**Comment by bitfort** [comment]
SWG Notes:

Resnet - 5 (both SGD and LARS)
SSD - 5
Maskrcnn - 5
Transformer - 10
GNMT - 10
Minigo - 10

**Comment by cliffwoolley** [comment]
Note that the Reinforcement learning (Minigo) number should be updated on https://github.com/mlperf/policies/blob/master/training_rules.adoc#11-benchmark-results , where it still says 20.

**Comment by petermattson** [comment]
Effectively a duplicate of #155.

**Comment by petermattson** [comment]
On second thought, reopen and make active to serve as reminder to get DLRM and BERT number of runs into rules.

**Comment by petermattson** [comment]
Duplicate of #297
