### ISSUE TITLE
Mask R CNN mask representation

### ISSUE THREAD

**Issue by petermattson** [mlcommons/training_policies#206]
MLPerf permits using different data formats. One way to represent the Mask R CNN mask is as a polygon. Another ways to represent it is as a scalable bitmask. We'd like a clarification that both are permitted.

**Comment by bitfort** [comment]
SWG Notes:

We recognize that there is flexibility in different data formats; approaches such as scalable bit masks or polygons fall within this flexibility given to submitters.

**Comment by frank-wei** [comment]
Submitted a PR #224
