### ISSUE TITLE
Submission Rules Delta

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#208]
TODO: link

**Comment by bitfort** [comment]
Link: https://docs.google.com/document/d/1UZ4O3nYzYRE6nVdkCCcd5LaZtC_RWOexyIvZVDurcDg/edit#heading=h.b8872h9ixor8

**Comment by bitfort** [comment]
SWG Notes:

The rules for submission have been updated. An overview of the changes for v0.6 are listed here:
https://docs.google.com/document/d/1UZ4O3nYzYRE6nVdkCCcd5LaZtC_RWOexyIvZVDurcDg/edit#heading=h.b8872h9ixor8

Plus, there is a new directory structure in the submission rules. 
https://docs.google.com/document/d/1YNGymVFuQdoH7tPFHWk6siSkFdvyHqKi3FuBTXaoxfM/edit

See document.

**Comment by petermattson** [comment]
No action required.
