### ISSUE TITLE
SSD mid-epoch changes

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#210]
SSD Reference does some things mid epoch, can this be pushed to epoch end/start?

**Comment by bitfort** [comment]
SWG Notes:

Learning rate, evaluation can occur in the middle of epochs for SSD reference (esp if changing batch size). We recognize that submitters may use approximate placement in the epoch (or at the end of the epoch). While we don't have a formal definition here, we expect placement to be "close". We intend to give a lot more latitude to doing this later than the reference than we intend to give to doing this in a way which brings events earlier than the reference.

**Comment by petermattson** [comment]
Handled by reference changes.
