### ISSUE TITLE
[inference] clarify the number of outstanding queries allowed.

### ISSUE THREAD

**Issue by christ1ne** [mlcommons/training_policies#217]
My understanding is that:

Single Stream: 1 outstanding query allowed
Multi Stream: 1 outstanding query allowed
Server: X outstanding queries allowed with X as the total number of queries. There is no limit.
Offline: there is only 1 query sent in total so not applicable.  @briandersn

**Comment by tjablin** [comment]
This matches my understanding. There was a proposed liberalization for Multi-Stream, but it didn't seem like there as a lot of enthusiasm for it in the WG.
