### ISSUE TITLE
Minigo 19x19 for v0.7

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#229]
How/if scale up minigo to 19x19 for v0.7.

**Comment by bitfort** [comment]
SWG Notes:

Generally people are okay with this change. We delegate to special topics to handle this process. Will report back with rough plan and progress as appropriate.

**Comment by jonathan-cohen-nvidia** [comment]
@bitfort this can be closed.

**Comment by petermattson** [comment]
Obsolete, we scaled it up.
