### ISSUE TITLE
Timeline for v0.7

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#230]
When is the submission deadline for v0.7?

**Comment by bitfort** [comment]
Initial Discussion on previous timeline was here:
https://github.com/mlperf/training_policies/issues/168

**Comment by bitfort** [comment]
SWG Notes:

Sept is the inference review month. August is too soon. This ball parks October on the early end, and early 2020 on the late end.

**Comment by frank-wei** [comment]
SWG Notes:
Most likely to park in 
1) Nov 1st submission, Dec 4th release, benchmarks finalize on Sep 1st.

**Comment by bitfort** [comment]
SWG Notes:

Closing due to duplicate; https://github.com/mlperf/training_policies/issues/242
