### ISSUE TITLE
Enforce compliance with script

### ISSUE THREAD

**Issue by frank-wei** [mlcommons/training_policies#241]
1. metadata  
2. logging details 
3. directories structure 
4. multi-nodes may have different information that scripts should be able to handle it.

**Comment by jonathan-cohen-nvidia** [comment]
Additionally would like to check that all hyperparameters are logged correctly and that settings are legal. 

All submission logs have to be clean on this verification script or they are rejected automatically (i.e. not reviewed or considered)

Ideally script would be ready along with reference implementations 3 months prior to submission.  All references should therefore be passing with the compliance script to be considered feature complete.

**Comment by petermattson** [comment]
Not done yet, but should be done soon. Need to add run requirement to rules.

**Comment by jonathan-cohen-nvidia** [comment]
This should basically be done.

**Comment by bitfort** [comment]
SWG:

This is done thanks to Marek!
