### ISSUE TITLE
Optimizer alignment

### ISSUE THREAD

**Issue by petermattson** [mlcommons/training_policies#243]
E.g. SGD TF vs pyTorch
Possibly define the equation

**Comment by frank-wei** [comment]
https://docs.google.com/spreadsheets/d/1be3ueG_NXY1Ei7rVem7R9FC5Xymu5d8naFaD645wFr0/edit#gid=0

WG Notes:
1. The link lists the difference of different optimizer implementation. 
2. Review the implementations, theoretically, we should not allow the differences exist.

**Comment by petermattson** [comment]
We're planning to fix LARS in TF in time for 0.7. Yeah, aligned optimizers!
:-)
Best,
Peter

**Comment by jonathan-cohen-nvidia** [comment]
I submitted a PR with proposed language to formalize this.
https://github.com/mlperf/training_policies/pull/264

**Comment by bitfort** [comment]
SWG Notes:

The proposal here proceeds as follows:

(1) Adopt a framework where we have a (per-benchmark) list of allowed optimizers and require people to prove equivalence to a listed optimizer to use another optimizer. 
(2) After adopting this framework, we discuss what optimizers appear on the list.

We propose the following timeline for v0.7:

Dec 12th: we vote adopting the framework and adopting a deadline of (submission - 3 moths) to freeze the optimizer list in the framework.

**Comment by jonathan-cohen-nvidia** [comment]
See updated PR: https://github.com/mlperf/training_policies/pull/277

Remaining work is 
- finalize this for DLRM & BERT
- Decide on allowable optimizer for RN50
- Close on Adam issue

**Comment by bitfort** [comment]
We agree we want a table.

AI(Everyone) - Review this table for Feb 13th discussion of table contents.

**Comment by petermattson** [comment]
Obsolete, table exists and appears to be complete.
