### ISSUE TITLE
Reviewer assignment guarantee

### ISSUE THREAD

**Issue by jonathan-cohen-nvidia** [mlcommons/training_policies#250]
Each Closed submission should have at least an assigned reviewer, selected from among the other submitters.  This is to guarantee that all submissions get reviewed.

Maybe if all submissions have to match reference convergence and logs have to pass an automated check, then there isn't much to do for non-controversial submissions.  In which case this requirements becomes quite easy to meet.

**Comment by bitfort** [comment]
SWG Notes:

We want to make sure anyone is free to review anything they want. We do want to make sure a submission isn't left behind, though. We may want to borrow what is being made for Inference. 

We will discuss the Inference WG's proposal once they have a proposal.

**Comment by bitfort** [comment]
Example language for rules:

Every submission gets a review by another submitter. If you submit, you may have to do a review as assigned by the review committee. The review committee will strive to match the amount of review work to the amount of work put into the submission. Any submitter is free to review any other submitter, in addition to any assigned reviews. 

Example Algorithm: the review committee will:
- Stack rank by number of submissions
- Assign reviewers in pairs walking down the stack rank
- If an odd number of reviewers, the bottom 3 in the stack rank will review each other.

**Comment by petermattson** [comment]
Move this to a general policy issue to add to submission rules
