### ISSUE TITLE
Clarify evaluation rules

### ISSUE THREAD

**Issue by petermattson** [mlcommons/training_policies#26]
(1) Is it timed? (Currently yes)
(2) Can it be pipelined with epoch execution?

**Comment by bitfort** [comment]
Evaluation has to be timed (i.e. the clock cannot be stopped), but you can hide latency by doing evaluation concurrently with other tasks such as training.

**Comment by bitfort** [comment]
Re-opening this issue for tracking.

**Comment by bitfort** [comment]
SWG:

Close a duplicate to existing issues.
