### ISSUE TITLE
Adam Equivalence

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#266]
Original Pytorch Adam doesn't match paper; resnet50 reference uses this different optimizer. Recently, pytorch changed Adam (to match paper). Slightly different numerics. TF matches what pytorch used to do; TF explicitly documents that they do not implement Adam's numerics as described by the paper.

Currently, latest pytorch and TF differ in Adam implementations and numerics. 

(1) Allow both optimizers -- non ideal from an equivalence perspective. 
(2) Implement "MLPerf Adam" which should be used for in the framework which differs. (either (a) create one for TF, or (b) create one for pytorch) (downside is adding engineering work)
(3a) Have the frameworks change default Adam (unlikely)
(3b) Add a special flag for compatibility (to TF for paper adam, or to pytorch for tf style adam)

AI(everyone) prepare for vote next week.

**Comment by bitfort** [comment]
Proposal:

Create a pytorch adam optimizer (which matches tensorflow) and have MLPerf submitters using pytorch "plug in" this optimizer.  

We will move forward with this proposal; pending details who makes pytorch optimizer.

**Comment by bitfort** [comment]
We are waiting on investigation into this from FB/pytorch.

**Comment by bitfort** [comment]
AI(Victor) -- send out an email to sort out who is driving this and our plan here.

**Comment by jonathan-cohen-nvidia** [comment]
@bitfort Any update on this?

**Comment by bitfort** [comment]
AI(NV) - push forward on this, volunteered in John's absence.

**Comment by bitfort** [comment]
SWG direction to submitters: if you are using pytorch Adam, remember to see the allow optimizer table here:
https://docs.google.com/spreadsheets/d/1be3ueG_NXY1Ei7rVem7R9FC5Xymu5d8naFaD645wFr0/edit#gid=1978307898

This lists the optimizers which have been checked for equivalence. If you do not use one of these optimizers, you will have to check and ensure equivalence yourself.

**Comment by petermattson** [comment]
No further action required.
