### ISSUE TITLE
Submission Timeline

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#269]
This is tracking issue for determining the next training submission. 

We have been tentatively looking at options, including April 24th 2020. While the exact date hasn't been chosen, we do not expect to submit sooner than April 24th.

**Comment by bitfort** [comment]
The timeline is primarily influenced by the need to have a freeze and the need to have the new benchmarks ready. Special topics update is that benchmarks Minigo, Bert, DLRM, RNNT may be ready by Jan 27th, exact timeline TBD. 

It looks like we need a cutoff date for accept new benchmarks into v0.7.

**Comment by bitfort** [comment]
We are still looking at April 24th, 2020 as the submission, to hopefully be finalized today.

**Comment by bitfort** [comment]
We are still planning on at April 24th. The pending items are Minigo and Bert which are schedule-impacting discussions on going.

**Comment by bitfort** [comment]
Current Dates to keep in mind:
HP Proposals / amendments 2/21
Agreement on amendments by 2/28

**Comment by christ1ne** [comment]
Is optimizer proposal also due 2/21? @bitfort

**Comment by bitfort** [comment]
Current Dates:

Optimizer Proposal 1/24
HP Proposals / amendments 2/21
Agreement on amendments by 2/28
Submission Deadline 4/24
Publication Date 5/20

**Comment by bitfort** [comment]
HP Proposals / amendments 2/28 (fri)
Agreement on amendments by 3/6 (fri)
Submission Deadline 5/8 (fri)
Publication Date 6/3 (weds)

**Comment by bitfort** [comment]
HP Proposals / amendments 3/11 (weds) [Using the newly defined HP Bar]

**Comment by bitfort** [comment]
Final Plan:
April 24th (Friday) - HP Table "Freeze"
May 8th (Friday) - Declare Intention to Submit
June 26th (Friday) - Submission
July 22nd (Wednesday) - Publication

**Comment by petermattson** [comment]
No further action required.
