### ISSUE TITLE
Resnet Learning Rate Schedule

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#270]
It is underspecified if you can make the learning rate schedule faster in v0.7 for LARS resnet.

This is an example of a class of optimizations which are not handled well by MLPerf. This class seems too large to white-list or black-list individually. Perhaps a statement of principles or some "test" that can be applied to help determine if an optimization is allowed.

**Comment by bitfort** [comment]
AI(Google) -- propose clarifying rules around this.

**Comment by bitfort** [comment]
SWG:
This is fixed by the HP Table.

**Comment by petermattson** [comment]
No further action required.
