### ISSUE TITLE
Potential delay in the training submission deadline?

### ISSUE THREAD

**Issue by christ1ne** [mlcommons/training_policies#279]
Due to the corona virus in China,  Intel training engineering has been stalled. I believe @frank-wei from Alibaba has the same concern. We do not have a concrete dates yet since we are not sure if the team will actually be back to work on Feb 10.

**Comment by bitfort** [comment]
It sounds like more information is needed to fully understand this impact. Let's revisit this next week with more information.

**Comment by bitfort** [comment]
Concretely, we are discussing May 8th for submission. This would result in a 2 week shift of the publication date to June 3rd. Please be prepared for a final decision next week.

**Comment by bitfort** [comment]
We have decided to move the deadline by two weeks. This will NOT move the inference deadlines. 

The new submission deadline is May 8th, 2020. The new publication date is June 3rd, 2020.

**Comment by petermattson** [comment]
No further action required.
