### ISSUE TITLE
MiniGo: Allow Tensorflow 2.0 patches in Tensorflow 1.15 within minigo 

### ISSUE THREAD

**Issue by rnaidu02** [mlcommons/training_policies#283]
1. Intel depend on some features in TensorFlow 2.x to run minigo, some are related to performance and some are related to bug fixes.
2. MLPerf Minigo reference implementation uses tensorflow-1.15.0.  In building C++ selfplay code, source code of tensorflow-1.15.0 is downloaded and build with C++ selfplay code.
3. Google says there is no near term plan to upgrade tensorflow version to 2.0 (https://github.com/tensorflow/minigo/issues/850)
4. Since current Minigo is with TF 1.15.0 , what we plan to do is provide a couple of patches that contain the feature/bug fixes in TF 2.x to org_tensorflow in WORKSPACE folder of minigo code.

**Comment by bitfort** [comment]
SWG Notes:

See the rules on details, but in general you would need to create a PR against a public repo and build against the commit in that PR. Also see the submission rules to understand the letter and spirit of the rules.

**Comment by petermattson** [comment]
No further action required.
