### ISSUE TITLE
Minigo real games played for each model should be logged and consider a tunnable hyperparameter

### ISSUE THREAD

**Issue by rnaidu02** [mlcommons/training_policies#286]
Among minigo hyperparameters, min_games_per_iteration (=8192) only restrict the minimum number of games should be played before a new training iteration can sample from.
https://github.com/mlperf/training/blob/master/reinforcement/tensorflow/minigo/ml_perf/flags/19/train_loop.flags#L9

However the reference implementation allows continuation of selfplay on the same model that creates more games until training iteration is finished. So the real number of games played for each model is an open HP [8192, +inf), which would affect the varity of samples.

Thus the real number of games played should be printed in the log to make reproduce a result possible, and should be considered a tunnable HP that fits HP stealing rule. The output in the logging could be something like:
"X games played for model 18"
"Y games played for model 19"
"Z games played for model 20"
...

https://github.com/mlperf/policies/issues/23

**Comment by bitfort** [comment]
We have a current proposal being considered for this. It is named as "actual_selfplay_games_per_generation", this has a minimum value of 8192. It can be set as high as the submitter wants. We will formalize this in the next week or 2 in the rules, pending discussion and review. It will also be present in the log files.

**Comment by bitfort** [comment]
This has been finalized in the HP list as actual_selfplay_games_per_generation;
https://docs.google.com/spreadsheets/d/128r_G1KEE0C1PzuTnBGybeNsT-mXeORZhmWnqDgu8Ok/edit#gid=540034374

**Comment by petermattson** [comment]
No further action required.
