### ISSUE TITLE
DeepSpeech 2 isn't a benchmark

### ISSUE THREAD

**Issue by TheKanter** [mlcommons/training_policies#289]
DeepSpeech 2 isn't in v0.5 or any version of MLPerf. Please update documentation to be consistent.

**Comment by bitfort** [comment]
SWG Agrees to remove deepspeech 2 from our benchmark lists.  

https://github.com/mlperf/training_policies/blob/master/training_rules.adoc

**Comment by petermattson** [comment]
Deepspeech 2 is not currently in rules, so all good.
