### ISSUE TITLE
Initial PyTorch reference implementations

### ISSUE THREAD

**Issue by ddutta** [mlcommons/training_policies#29]
Supporting Organizations: Stanford, Cisco, Nvidia, FB, MSFT .... 

Daniel Kang (Stanford) volunteered to help out. Debo Dutta (Cisco) also volunteered resources (e.g. engineers, interns) to help. FB/Nvidia was very happy to provide feedback if needed.

**Comment by tremblerz** [comment]
Hi! I am intern at Cisco. Working on porting [transformer](https://github.com/mlperf/reference/tree/master/translation/) implementation to PyTorch right now.

**Comment by bitfort** [comment]
The submitters working group is recommending that all ports be added to the community repo https://github.com/mlperf/community

**Comment by bitfort** [comment]
Re-opening this issue for tracking.

**Comment by petermattson** [comment]
Not really a rules issue.
