### ISSUE TITLE
Finalization of Logging and Compliance

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#293]
Submitters WG review of our logging and compliance for v0.7.

* Review the logging spec document (Discuss May 14th, Finalize May 21st)
* Migrate to thew new logging client (https://github.com/mlperf/logging)
* Try out new single log compliance checker (https://github.com/mlperf/logging)

**Comment by petermattson** [comment]
Recommend we update rule to require use of logging checker for all submissions.

**Comment by bitfort** [comment]
It is done.
