### ISSUE TITLE
Relax the rule in the context of COVID

### ISSUE THREAD

**Issue by danielcdh** [mlcommons/training_policies#295]
The productivity of many MLPerf participants have been severely affected by COVID-19 situation. To accommodate this special situation, I propose to relax the rule in MLPerf 0.7 training round to:

As soon as the submitted model is mathematically equivalent with any closed category submission in MLPerf 0.6, it is considered compliant.

The reasoning behind it:
1. If a model is accepted by MLPerf 0.6, it's considered as compliant already
2. HP table is not implemented for MLPerf 0.7
3. There are models implemented in different frameworks (TF, Pytorch, MxNet, etc), validating every single bits of one framework to match another requires a lot of time and effort
4. This allows participants to just pull out an existing submission and tune it on their framework without spending significant engineering to validate its compliance, which does not help the company's core business. This is specifically important not only for large companies but also for small companies where resource is usually a constraint, especially in the COVID situation.

In the long run, after COVID situation is over, we can keep finalizing HP table, make all the models behave exactly the same between different frameworks and apply more strict compliance rule.

**Comment by bitfort** [comment]
SWG:

AI(PM) start a thread

**Comment by petermattson** [comment]
Agreed we need go forward and manage as best we can.
