### ISSUE TITLE
Convergence issue with  MXNet ResNet-50 using Lars with 4K Batch size

### ISSUE THREAD

**Issue by rnaidu02** [mlcommons/training_policies#296]
MXNet Resnet50 Lars with 4K BS cannot converge within 60 epochs, following are the details:

Intel team used MXNet build in mxnet.optimizer.lars and mxnet.lr_scheduler.PolyScheduler, as well as resnet50_v1b model from MXNet GluonCV model zoo. In terms of Hyper Parameters, we used the HPs from Google’s last submission with 4K BS (128 x 32 tpu):
https://github.com/mlperf/training_results_v0.6/blob/master/Google/results/tpu-v3-32/resnet/result_0.txt

We want to know if we are missing something to reproduce the same convergence results as NV and Google when using the same LARS hyperparameter configurations for the ResNet-50 model from MXNet GluonCV model zoo.

**Comment by bitfort** [comment]
There was some discussion on this during the meeting to try to understand the issue. We can follow up off line based on what was discussed.

**Comment by bitfort** [comment]
Is there still an issue here? Please reach out over email.

**Comment by bitfort** [comment]
AI(Christine) Follow up over email.

**Comment by christ1ne** [comment]
we are OK to close.
