### ISSUE TITLE
Number of Runs for v0.7

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#297]
The current proposal is:

Number of runs for v0.7.
Resnet - 5
Maskrcnn - 5
SSD - 5
Transformer - 10
GNMT - 10
Minigo - 10 (previously 20)
DLRM - 5 (NEW)
BERT - 10 (NEW)

Please review for decision next week.

**Comment by bitfort** [comment]
AI(Everyone) - Review DLRM number of runs.

**Comment by frank-wei** [comment]
Can we list the steps of validation needed for BERT and DLRM?
In DLRM, how many validation steps we need? Is it related to batch size?
In BERT, how many validations we need? 1 per epoch?

**Comment by christ1ne** [comment]
We have agreement on DLRM for 5 runs over email.

**Comment by bitfort** [comment]
SWG:

Number of runs for v0.7.
Resnet - 5
Maskrcnn - 5
SSD - 5
Transformer - 10
GNMT - 10
Minigo - 10
DLRM - 5
BERT - 10
