### ISSUE TITLE
Update/change documentation for v0.7

### ISSUE THREAD

**Issue by TheKanter** [mlcommons/training_policies#299]
https://github.com/mlperf/training_policies/blob/master/training_summary.adoc AND
https://github.com/mlperf/training/blob/master/README.md AND
https://github.com/mlperf/training_policies/blob/master/training_rules.adoc

Refer to the v0.5 benchmarks and rules. We should update to v0.7. Do we need to mention hyperparameter tables, etc.?

**Comment by bitfort** [comment]
We recognize that these documents are out-of-date with the rules. We should really do this! We are working on prioritizing this.

**Comment by bitfort** [comment]
Double check this in the rules.

**Comment by petermattson** [comment]
Updated or deleted obsolete documents. Training rules are being updated through specific issues.
