### ISSUE TITLE
Update official rules to match optimizer review table

### ISSUE THREAD

**Issue by jonathan-cohen-nvidia** [mlcommons/training_policies#318]
Analysis here: https://docs.google.com/spreadsheets/d/1be3ueG_NXY1Ei7rVem7R9FC5Xymu5d8naFaD645wFr0/edit#gid=1978307898

needs to be copied into rules doc - rules doc is slightly out of date.

**Comment by jonathan-cohen-nvidia** [comment]
See PR: https://github.com/mlperf/training_policies/pull/319

**Comment by bitfort** [comment]
SWG:

The PR was merged. This has been done.
