### ISSUE TITLE
Postpone Sentiment Analysis Benchmark

### ISSUE THREAD

**Issue by petermattson** [mlcommons/training_policies#32]
Benchmark is presently too small (converges in ~2 minutes) to effectively guide hw/sw design.

Also, benchmark has weakest justification among current list and there is some benefit to reducing engineering cost/risk for submissions.

**Comment by gdiamos** [comment]
Note that we are looking into adding a larger public dataset based on DBPedia with data augmentation.    DBPedia requires significant data preprocessing, so the ETA on this is at least 1 month.
