### ISSUE TITLE
Consistency between training_rules and submission_rules

### ISSUE THREAD

**Issue by jonathan-cohen-nvidia** [mlcommons/training_policies#320]
Currently there are two separate rules docs for MLPerf :
https://github.com/mlperf/training_policies/blob/master/training_rules.adoc
https://github.com/mlperf/policies/blob/master/submission_rules.adoc
 
They appear to be mostly covering separate topics, but they don’t reference each other and there is no indication of what the intended function is of each.  I’m not sure they are entirely consistent with each other, either.

Comment from @petermattson:
Intent is:
Training rules is specifically about what to implement for MLPerf training.
Submissions rules are generic to all MLPerf benchmarks for things like code availability and review process.

Cross references in intro with description at a minimum would be good and easy

**Comment by bitfort** [comment]
SWG:

There should be pointers between both documents.
