### ISSUE TITLE
DLRM - remove unnecessary eval metrics in submission

### ISSUE THREAD

**Issue by christ1ne** [mlcommons/training_policies#321]
Hello all,

The DLRM code currently has multiple metrics in the eval step. I think per the training rules we can remove the unnecessary ones and only keep the one per the target accuracy requirement. 

just want to confirm in the WG.

**Comment by bitfort** [comment]
SWG:

There are multiple metrics computed during eval for DLRM in the reference, we clarify that the only metric that needs to be computed are the metrics directly needed for the stopping criteria.

**Comment by bitfort** [comment]
Make this documented in the rules.

**Comment by petermattson** [comment]
Fixed per PR above.
