### ISSUE TITLE
update all tables in the rules doc to contain all benchmarks

### ISSUE THREAD

**Issue by christ1ne** [mlcommons/training_policies#322]
recommend to do so in the meeting so that there is no ambiguity. 

https://github.com/mlperf/training_policies/blob/master/training_rules.adoc#3-benchmarks

**Comment by jonathan-cohen-nvidia** [comment]
This document is also now very out of date and we should fix it.
https://github.com/mlperf/training_policies/blob/master/training_summary.adoc

**Comment by bitfort** [comment]
SWG:

The table has to be updated to list default models.
