### ISSUE TITLE
exception to the preview requirement of submitting again under available

### ISSUE THREAD

**Issue by christ1ne** [mlcommons/training_policies#323]
Intel submitted a preview result for minigo for under preview category. Considering minigo has been changed significantly, especially the run time, so I think it is reasonable not to require minigo submission again in this round as a mandatory requirement.

**Comment by bitfort** [comment]
SWG:

Our understanding is that the hardware is GA now; resubmitting for performance comparison in this particular case is not valid because the benchmark has changed so much.
