### ISSUE TITLE
Clarify Logging Source of Truth for Logging

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#324]
We want to clarify in the rules that logs must exist and follow our verifier / spec.

**Comment by bitfort** [comment]
SWG: 

The rules will direct users to pass the log verifier code before submitting, they may have warnings but not errors. Try  to not have warnings.

**Comment by petermattson** [comment]
Fixed with PR #31 to submission rules

**Comment by petermattson** [comment]
Closed by PR to policies doc.

**Comment by jonathan-cohen-nvidia** [comment]
The link above to the PR is incorrect.  Should be:
https://github.com/mlperf/policies/pull/31
