### ISSUE TITLE
Rules state that 1000 or 1001 classes are allowed for RN50 in 2 places

### ISSUE THREAD

**Issue by jonathan-cohen-nvidia** [mlcommons/training_policies#329]
Minor point, but this is now in 2 places:
https://github.com/mlperf/training_policies/blob/master/training_rules.adoc#94-equivalence-exceptions
and
https://github.com/mlperf/training_policies/blob/master/training_rules.adoc#12-appendix-benchmark-specific-rules

We should delete one of them. @petermattson

**Comment by petermattson** [comment]
Good catch.
https://github.com/mlperf/training_policies/pull/333

**Comment by petermattson** [comment]
Promoting this to rule change so group can confirm PR, since no actual content change.

**Comment by petermattson** [comment]
This has been fixed by a merged PR.
