### ISSUE TITLE
Closed division numerical representation dependency 

### ISSUE THREAD

**Issue by ad6fp** [mlcommons/training_policies#33]
Section 8.2 of the user guide specifies that the same loss function as used in the reference must be used in the closed division.  Since IEEE half-precision frequently requires a loss function that is scaled to ensure convergence while single-precision does not require scaling this rule presents a dependency between the reference implementation and the numerical representation.  It would be preferable to decouple the numerical representation used from the reference implementation.

**Comment by bitfort** [comment]
The submitters working group has reached consensus that submitters are allowed to add a scaling term to compensate for different precisions. The WG can provide additional clarification on scaling as necessary.

**Comment by petermattson** [comment]
Fixed by PR "Added precision whitelist and scaling policy #73"
