### ISSUE TITLE
change the offline evaluation starting point without affecting TTT

### ISSUE THREAD

**Issue by christ1ne** [mlcommons/training_policies#335]
In some benchmarks like minigo, we'd like to start offline evaluation at a later point as implemented in the reference. Here is an example: the current minigo starts evaluation at 20th iteration and we'd like to start evaluation at the 50th iteration.
The reported TTT won't change as the evaluation is offline. However, the software running time can be reduced to lower the cost of submission. 
I recommend an explicit rule update to clarify this point.

**Comment by bitfort** [comment]
SWG:

We will add to the rules that you don't need to do unnecessary offline evaluations.
