### ISSUE TITLE
Section 5.11 in submission_rules is blank.

### ISSUE THREAD

**Issue by jonathan-cohen-nvidia** [mlcommons/training_policies#340]
This file is under mlperf/policies, not mlperf/training_policies, but filing here so it gets attention.

https://github.com/mlperf/policies/blob/master/submission_rules.adoc#511-source-code-requirements-for-training-inspection

Shouldn't be blank. @petermattson would be good to discuss on Thursday.

**Comment by bitfort** [comment]
Fill this in please. 

Will say roughly: Include all the code and other things too.

**Comment by petermattson** [comment]
Fixed by mlperf/policies PR #33.
