### ISSUE TITLE
Update hyper parameters in DeepSpeech model to reflect production settings

### ISSUE THREAD

**Issue by gdiamos** [mlcommons/training_policies#35]
The current implementation of DeepSpeech is close to the configuration originally deployed in Baidu, but there are several essential differences.  Specifically:

1) The layer sizes are too small.  GRU layers should be in the range of 2048-3560 hidden units.
2) Bidirectional models are not deployed in production due to latency issues.  See the original paper for details on how to replace them with alternatives such as row convolutions.  As a stopgap solution, simply removing the backwards direction would resolve the latency issue although we would expect it to have a large impact on accuracy.
3) Batch normalization is useful for training, but has generalization issues for deployment.  We propose simply removing it.  Note that this may require shallower RNN networks, or other GRU/optimization hyper parameter search to find models that can achieve similar accuracy.

**Comment by nvpaulius** [comment]
We should move this issue under mlperf/reference rather than mlperf/plicies (or close this one and file a new issue under reference).
