### ISSUE TITLE
All ports of mlperf reference implements should be moved to the community repo.

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#37]
We are very grateful for everyone who put in effort to create ports for the MLPerf reference implementations. 

I propose that any ports of reference implementations to another framework (or for that matter other implementations of the reference) should be committed to https://github.com/mlperf/community ; existing PRs to the reference repo should moved there. 

The goal with this proposal is to avoid confusion as to which implementation is correct. The current rules state that the reference implementations are correct by definition -- have multiple reference implementations could confuse this.

**Comment by christ1ne** [comment]
Agree. I believe there are multiple TF ports and I hope to see them all at /community.

**Comment by bitfort** [comment]
The Submitters working group recommends all non-reference code (e.g. ports to other frameworks) be submitted to the community repo.

**Comment by petermattson** [comment]
This has been done.
