### ISSUE TITLE
Choose Timeline for v1.0

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#380]
See Discussion on this document:

https://docs.google.com/spreadsheets/d/1W8L8SBIrgbJ_f_-2hUt8SqLNkzAvsKNkQ0A6pKWz9_8/edit#gid=0

**Comment by bitfort** [comment]
SWG:

Current Proposal is 5/21/2021.

**Comment by bitfort** [comment]
SWG:

Agreed final contingent on Inference WG timeline.

**Comment by bitfort** [comment]
SWG:

No strong objection reported from inference WGs.

**Comment by johntran-nv** [comment]
Official dates for Training v1.0 are:
1/21: reference code and rules freeze, with some rules exceptions that were still open
5/21: submission
6/23: publication

This was documented in the MLCommons calendar (on the google drive) as well as the Training WG minutes.

Closing.
