### ISSUE TITLE
Market Understanding for Roadmap

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#383]
We list our questions here:

https://docs.google.com/document/d/1395kWYtfSNGw0ZO7B-3kxoCm0EBdDhgE1KxE7VXM79M/edit?usp=sharing

**Comment by tjablin** [comment]
There are no questions in the linked doc.

**Comment by bitfort** [comment]
SWG:

We are letting the Advisory Groups handle the understanding here. We are looking forward to an update from them.
