### ISSUE TITLE
PROPOSAL Add 3D Unet for v1.0

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#388]
There is a proposal to add 3D Unet for 1.0; tracking discussion here.

**Comment by johntran-nv** [comment]
For 10/8/2020, Pablo will attend and give an update, along with a call for submitters to form a working group.

**Comment by bitfort** [comment]
SWG:

Forming a Task Group for Next Week (Oct 15).

**Comment by bitfort** [comment]
SWG:

Update from Pablo;
- Currently 3 participants in the task group for the benchmark, meeting for 3 weeks (thursday meeting)
- Shared differences between training and inference version of the model
- Instance norm is a problematic layer for normalization when scaling for training (do we want batch norm?)
- Leaky relu v. relu doesn't make a difference, making to relu may be simpler for everyone
- Changing instance norm shows a difference, distributed batch normal preforms better at scale
- Making these changes is a trade-off; batch norm preforms more poorly in single-GPU use case.

**Comment by johntran-nv** [comment]
This is already well under way for v1.0.  Closing, since I don't see a benefit from keeping this issue open.
