### ISSUE TITLE
SSD validation schedule

### ISSUE THREAD

**Issue by johntran-nv** [mlcommons/training_policies#396]
Do we want to move to every 5th epoch or keep the v0.7 schedule?

**Comment by bitfort** [comment]
SWG:

We're going to move to every 5th epoch.

**Comment by bitfort** [comment]
SWG:

We will check if the original requestor still cares about the issue, since SSD is on it's last round.

**Comment by bitfort** [comment]
SWG:

This will follow resnet evaluation rules except SSD has a stride of 5 (as opposed to resnet stride of 4).

Will revisit next week to finalize.
