### ISSUE TITLE
BERT dataset is missing.

### ISSUE THREAD

**Issue by johntran-nv** [mlcommons/training_policies#403]
We need to find a place to host it.  Last suggestion was MLCommons.

**Comment by johntran-nv** [comment]
filing in training_policies but there's also an issue in training already: https://github.com/mlperf/training/issues/377.

**Comment by bitfort** [comment]
SWG:

We will consult internally at MLCommons for the appropriate place to host this, such as at MLCommons. David will get back.

**Comment by bitfort** [comment]
SWG:

This continues be blocked on finding where to host it. We have made some progress with legal.

**Comment by TheKanter** [comment]
The Wikipedia data set for BERT is available here: https://drive.google.com/drive/folders/1oQF4diVHNPCclykwdvQJw8n_VIWwV0PT?usp=sharing Note that you must be a member of MLPerf Training to access.

**Comment by johntran-nv** [comment]
One remaining question: do we intend to make this available to the public as well?  @TheKanter

**Comment by shoveller86** [comment]
> The Wikipedia data set for BERT is available here: https://drive.google.com/drive/folders/1oQF4diVHNPCclykwdvQJw8n_VIWwV0PT?usp=sharing Note that you must be a member of MLPerf Training to access.

How to be a member of MLPerf Training?

**Comment by bitfort** [comment]
You can get started here;
https://mlcommons.org/en/get-involved/#getting-started

Please let me know if you have any questions!

**Comment by shoveller86** [comment]
> You can get started here;
> https://mlcommons.org/en/get-involved/#getting-started
> 
> Please let me know if you have any questions!

Thank you, I'll try to join in Member
