### ISSUE TITLE
RNN-T Working Group call for participation

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#404]
Proposal: Wednesday 9am PST

**Comment by bitfort** [comment]
SWG:

Discussion of making a sub working group to training of limited duration for creating new benchmarks. The exact solution isn't clear. 

An email will be sent asking for people who want to be involved in such a working group, such having experience in the area, caring about the benchmark or possibly planning to submit in the future.

**Comment by johntran-nv** [comment]
Call for submitters email was sent out on 11/13/2020.
