### ISSUE TITLE
Definition of "non-stateful" nodes

### ISSUE THREAD

**Issue by ad6fp** [mlcommons/training_policies#43]
Are saved activations considered "non-stateful" nodes of the training graph so that techniques like recomputation of the node state instead of saving the state are permitted in the closed division ?

**Comment by bitfort** [comment]
SWG:

Our general recommendation is that if provably mathematically equivalent, you can do it. Our understanding is that this is a systems trade-off between compute and memory. Please confirm that our understanding is correct.

**Comment by ad6fp** [comment]
Victor -

This doesn’t seem to address the definition of a “non-stateful” vs. a “stateful” node.
Are the only “stateful” nodes of the training graph the weights?
Will the wording be modified to be “mathematically equivalent” rather than “changes to non-stateful”.

Yes, the tradeoff enables a reduction in activation storage at the cost of more compute.

Gary Lauterbach
gary@cerebras.net<mailto:gary@cerebras.net>
CTO and Co-Founder
Cerebras Systems




On Aug 2, 2018, at 11:50 AM, Victor Bittorf <notifications@github.com<mailto:notifications@github.com>> wrote:


SWG:

Our general recommendation is that if provably mathematically equivalent, you can do it. Our understanding is that this is a systems trade-off between compute and memory. Please confirm that our understanding is correct.

**Comment by petermattson** [comment]
Sending back to WG to confirm, but presumably yes, only the weights.

**Comment by bitfort** [comment]
SWG:

If it is mathematically correct, it is fine to do.
