### ISSUE TITLE
[image classification] decode jpeg image in preprocessing

### ISSUE THREAD

**Issue by delock** [mlcommons/training_policies#434]
Hi, I want to get clarification whether decode jpeg image and install it in raw (RGB) format in data preprocessing is conforming to training_policies.  Decode a jpeg image is part of reference implementation and is non-random part of the data processing, so my understanding is it is allowed.   Want to get confirm from WG.

**Comment by johntran-nv** [comment]
Hi @delock , we discussed this last week, and agreed that jpeg decode alone can be considered a data layout transformation, which is explicitly allowed by the rules, specifically https://github.com/mlcommons/training_policies/blob/master/training_rules.adoc#61-data-state-at-start-of-run.

Note that data augmentation of any kind would invalidate this.  

Does that answer your question?

**Comment by delock** [comment]
@johntran-nv  Thanks, that answers my question.
