### ISSUE TITLE
Target quality for SSD

### ISSUE THREAD

**Issue by petermattson** [mlcommons/training_policies#46]

**Comment by bitfort** [comment]
SWG: 

Still pending. More information will be forth coming.
The implementation in the SSD branch (of reference) will become the reference. You can start looking now if you're interested. It is implemented in pyTorch.

Other implementations of SSD (such as paddle paddle) may be put in the community repo. 

This will be discussed further in the next SWG meeting.

**Comment by nvpaulius** [comment]
Tentative target accuracy is 21.2% mAP (0.5:0.05:0.95 IoU), COCO 2017 validation data. We may adjust it once we have enough runs to assess run to run variance.

**Comment by bitfort** [comment]
SWG:

We will currently target 21.2% mAP (0.5:0.05:0.95 IoU), COCO 2017 validation data. This is subject to the overall variance scrub of all the benchmarks in the future (e.g. this may be slightly raised in the future).
