### ISSUE TITLE
Request for clarification of two points regarding RCP

### ISSUE THREAD

**Issue by fjtabaru** [mlcommons/training_policies#469]
1. Is a submission to open division free from RCP?

2. When we find a set of hyperparameters that gives a better RCP than the reference and use it to post a benchmark result, do we need to report the RCP prior to submitting?

We're planning to submit the result to MLPerf HPC, which submission deadline is Oct. 8.

**Comment by TheKanter** [comment]
I don't know if HPC is planning to use RCPs. Can you start a thread on the HPC mailing list?

**Comment by fjtabaru** [comment]
Thank you very much.
I'll do so.
