### ISSUE TITLE
[HPC][OpenCatalyst] Missing HP rule for LR decay factor

### ISSUE THREAD

**Issue by sparticlesteve** [mlcommons/training_policies#494]
The learning rate decay factor was mistakenly left out of the HP table for the OpenCatalyst benchmark, but is a very reasonable thing to tune and is usually allowed for other benchmarks.

I think we should allow to add a rule saying this parameter is unconstrained for HPC v2.0, despite being past the freeze deadline.

**Comment by azrael417** [comment]
I think it makes sense to make this parameter tunable. I do not see any big issues adding this to the tunable parameters list at this point in time since we are still early in the submission.

**Comment by sparticlesteve** [comment]
Turns out this wasn't really forgotten, but was hidden in the markdown rendering due to a bug in the table!
See #495
