### ISSUE TITLE
[HPC] Need a way to explicitly specify which version of Training rules apply to our HPC rules

### ISSUE THREAD

**Issue by sparticlesteve** [mlcommons/training_policies#496]
From the 2022-07-18 WG meeting:
- Probably use the snapshot at the time of hpc rules freeze
- But need to state this somewhere: 
- perhaps add a link/tag to the appropriate raining rules in the HPC rule doc

**Comment by memani1** [comment]
Added text in the rules doc with PR at #501.

**Comment by sparticlesteve** [comment]
Fixed in #501
