### ISSUE TITLE
Reference Repo Issues

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#52]
Currently the Submitters Working Group examines policy issues. We should also determine what to do about reference repo issues; do we
- Migrate them over here
- Manage/monitor both issues queues in the SWG
- Create a new group
- Something else?

**Comment by petermattson** [comment]
I booted an owners WG, will try and keep it mailing list focused. We should only handle official changes what a ref **should** do, not bug fixes, library versions, etc.
