### ISSUE TITLE
Submission Check List

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#57]
We should compile a shared check list which all submissions should go through to help engineers and other submitters.

I'll start off the list with the following, please do contribute to this list and we will discuss it in SWG :)

- Check Point Frequency
- Dataset Validation
- Framework Version (a release candidate)
- Were all caches flushed prior to each run?
...

**Comment by bitfort** [comment]
SWG:

We like the idea of a check list. A draft of a check list will be forthcoming.

**Comment by bitfort** [comment]
SWG:

This is duplicate with log lines.

**Comment by petermattson** [comment]
Clarifying title to cover things not handled by log lines, referring to results WG

**Comment by petermattson** [comment]
Closing as duplicate.
