### ISSUE TITLE
Grace Period

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#59]
Is there a grace period after submissions in which corrections can be made? Are submissions final once submitted? Can multiple submissions be made before the deadline (are all reported or only the most recent)?

**Comment by bitfort** [comment]
Initial idea;

Week 1: review others' submissions, at end give and get feedback 
Week 2: make changes
Week 3: re-run and re-submit

There will be mechanisms to prevent people from using this as a deadline extension and to limit the work to the feedback given.

**Comment by bitfort** [comment]
SWG:
  We will bump this issue up to the larger group to work with.

**Comment by petermattson** [comment]
Result WG to decide on schedule.

**Comment by petermattson** [comment]
Resolved by submission rules.
