### ISSUE TITLE
Improve Accessibility: Add translation to Chineses  

### ISSUE THREAD

**Issue by dylanzika** [mlcommons/training_policies#60]
Given that we would like ML perf to be accepted in other countries and around the world as a global standard, we should eliminate the language barrier and improve the accessibility to increase adoption in other countries/cultures.

In the spirit of Agile development maybe having a choice at the top of the page to select between US/EU and Chinese would be a good start. This is similar to how AnTuTu has two flavors of its webpage, one in English and one in Chinese.

WEI DAI Volunteered to do the translations for v1
Supported by: Peter Mattson, Vijay Reddi, WEI DAI

**Comment by petermattson** [comment]
Not a rules issue.
