### ISSUE TITLE
Rules and References for Preprocessing

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#63]
MLPerf Rules currently state:
https://github.com/mlperf/policies/blob/master/rules.adoc#preprocessing
"""
5.2. Preprocessing
All preprocessing time is included in the wall-clock time for a run result.

CLOSED: The same preprocessing steps as the reference implementation must be used.
"""

Also, informally in discussions we have been leaning on the guidance of "do what the reference does." 

The issue is that the rules are inconsistent with the reference implementations and the reference implementations are inconsistent with each other. 

- For example, some reference implementations time the process to "unzip" the dataset while others don't. Presumable the action of "unzipping" should be defined as being pre-processing or not being pre-processing and that definition should be applied consistently across references.
- The reference resnet does not count the time to pre-process imagenet.

While taking the position of "do what the reference does" is convenient from a committee and rules-making perspective, the reality of deferring to 11th-hour coding efforts presents challenges. And more generally, I believe there is a lack of clarity when and where you are allowed to deviate from the reference implementations.

**Comment by ddkang** [comment]
It sounds like this could be fixed by 1) changing all the reference implementations so unzipping isn't counted (I think it's uncontroversial that unzipping isn't related to ML performance), 2) updating the reference resnet timing to include the preprocessing.

Are there other specific issues you had in mind?

**Comment by bitfort** [comment]
SWG:

Downloading and unzipping should not be timed. Reference implementations should be changed to not time unzipping or downloading. 

We will propose a way to reduce the amount of pre-processing which is timed. This will be proposed in a way which will not give advantages to specific file formats and to prevent users from moving work that should be timed into the untimed pre-processing.

**Comment by bitfort** [comment]
SWG:
   - This will be revisited in whole for v1.0 -- this is intended to enable v0.5 and does not reflect our long term vision. 
   - Unless explicitly specified, all preprocessing should be untimed.
   - Untimed preprocessing can include arbitrary data reformatting provided that the reformat does not introduce new information or copies of the information. You may reorder fields or pad images, but may not reorder data items or add image distortions. You may not create copies for different epochs or different uses.
   - In general, any preprocessing that would be done once and reused in normal practice should be untimed.
   - In general, preprocessing that varies between runs in normal practice (e.g. random distortions) should be timed.

We will amend this next week with specific exceptions.

**Comment by petermattson** [comment]
Already fixed by prior issue #30. Closing as duplicate.
