### ISSUE TITLE
update rules to allow subset of benchmarks for submission

### ISSUE THREAD

**Issue by christ1ne** [mlcommons/training_policies#64]
quoted from the current rules:

11. Division Results
In order to report a division result, a benchmark score must be reported for each benchmark in the suite. The division score is the geometric mean of the benchmark results.

-----------------------

Since we already decided that a single summary score is not going to happen, we should update the rules to allow submissions for a subset of the benchmark suite to reflect that.

**Comment by bitfort** [comment]
SWG:
  There will be a rules update soon to reflect previous large group discussions on this. After it is updated, please re-file issues about this against the updated rules if you still have questions.

**Comment by petermattson** [comment]
Already updated as part of fix to #2. Closing as duplicate in effect.
