### ISSUE TITLE
Evaluation Time

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#71]
Evaluation can be expensive and it could be worth exploring solutions for this.

**Comment by bitfort** [comment]
SWG: 

Will discuss next week with additional thoughts and input.

**Comment by bitfort** [comment]
SWG:

Resnet evaluation is once every 4 epochs where the submitter may choose an offset from 0 to 3 epochs for the first evaluation. SSD evaluation follows the reference evaluation. All other benchmarks evaluate every epoch (restating what the reference does). 

Evaluation is on the clock -- specifically, the clock can only be stopped after an evaluation reaching or exceeding the target quality has been completed.

**Comment by petermattson** [comment]
Closing following change to reference.
