### ISSUE TITLE
NCF 30% Failures

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#77]
30% of the time NCF does not converge (over fits). Submitters should give direction on how to handle this situation. 

I propose we direct submitters to simply re-run NCF if it does not converge after 30 epochs.

**Comment by bitfort** [comment]
For context, we expect NCF to converge in about 8 to 14 epochs, so this is a factor of 2x buffer.

**Comment by bitfort** [comment]
SWG:

Submitters can run a certain number of times and average cross the ones which converged. We defer to special topics WG to clarify the specific methodology.

**Comment by christ1ne** [comment]
NCF rules says Run 100, use first 50 that converge

I'd like to clarify if it is about run pass percentage vs counts. E.g. need to pass 50% of submitted runs or submit however many rounds with 50 converged runs.

**Comment by petermattson** [comment]
The rule is literally run 100 times and the expectation is that at least 50 of those runs will converge. In practice, we see convergence above 70%. Please re-open and mark if still an issue.
