### ISSUE TITLE
Does CLOSE track of RL allow INT8 inference?

### ISSUE THREAD

**Issue by jgong5** [mlcommons/training_policies#79]
No changes to the model, just use 8-bit low-precision inference, activations and filters are quantized, is it allowed?

**Comment by petermattson** [comment]
Hi, jgong, can you please clarify? Specifically, are you asking about the training suite (with 10/31 deadline) or the inference suite (under development in inference working groups)?

**Comment by jgong5** [comment]
@petermattson It is about the training suite. In the RL workload (MiniGo), there are inference workloads with self-play and evaluation. Can we use INT8 inference for them? The SGD optimization part is still with fp32 though. Thanks.

**Comment by petermattson** [comment]
Hi Jiong Gong,

We're going to be discussing mini go in detail at the next MLPerf special
topic sessions Wednesday at 12. In particular, we'd really like to migrate
to C++ for the non DNN code and this presents timeline issues. Can you make
it?

Best,

Peter

**Comment by jgong5** [comment]
@petermattson I will check with my colleague representative who might attend the discussion meeting. What is the timezone for 12:00pm Wednesday?

**Comment by petermattson** [comment]
Thanks! Pacific.

**Comment by christ1ne** [comment]
I will attend on behalf of @jgong5

**Comment by bitfort** [comment]
SWG:

Defer to the group talking about Minigo.

**Comment by petermattson** [comment]
Conclusion is that int8 is allowed only for mini-go inference.

**Comment by jgong5** [comment]
@petermattson @christ1ne @bitfort Thank you all!

**Comment by petermattson** [comment]
Re-opening since not yet specified in the rules. All good, but will close via PR change to the rules.

**Comment by jackalcooper** [comment]
@petermattson Hi, Peter. How could people join the MLPerf special
topic sessions?

**Comment by petermattson** [comment]
Hi Jackal,

Thanks for your interest! Are you planning a 11/9 submission?

You can join the working groups here:
mlperf-special-topics@googlegroups.com
<https://groups.google.com/forum/#!forum/mlperf-special-topics>
mlperf-submitters@googlegroups.com
<https://groups.google.com/forum/#!forum/mlperf-submitters>

Best,

Peter

**Comment by jackalcooper** [comment]
@petermattson Thanks for your reply! Yes we are working very hard for the 11/9 submission. I applied to join the group. Please approve it if you are a manager of the google group.

**Comment by petermattson** [comment]
Hi Jackal,

WG chairs are approving people to join.

Are you targeting closed or open? What organization are you with? We're
trying to find all possible closed submitters so we can make sure it goes
smoothly.

Best,
Peter

**Comment by jackalcooper** [comment]
@petermattson Hi, Peter. We are targeting closed. To be more specific, classification task (resnet I think) and detection task (fasterRCNN and SSD). Our organization is OneFlow. We built a deep learning framework called OneFlow. It is built from scratch, not based on any existing deep learning frameworks. It has not been open-sourced yet which is also a concern [here](https://github.com/mlperf/policies/issues/125) .

**Comment by petermattson** [comment]
Added fix to doc, should have auto closed this.
