### ISSUE TITLE
Change number of runs for benchmarks to reduce variance

### ISSUE THREAD

**Issue by petermattson** [mlcommons/training_policies#85]
Need to specify number of runs. Strawman counts in Special Topics WG minutes.

**Comment by bitfort** [comment]
SWG:

This has been discussed in Special Topics WG. Briefly, we will increase the number of runs for benchmarks to reduce the variance in the score. The details behind this discussion are covered in the Special Topics WG. 

For closed, we defer to the special topics WG to set the number of runs per benchmark. The present Special Topics proposal will be written into the rules, subject to further discussion in WGs.
For open, we stay with the five runs per benchmark.
