### ISSUE TITLE
remove the word 'leaderboard' from 'MLPerf Training Rules'

### ISSUE THREAD

**Issue by christ1ne** [mlcommons/training_policies#91]
MLPerf results allows systems to be submitted with a its own scale information. It is not a competition to showcase most massive systems with the shortest training time. 

original text:
14. Submissions
The MLPerf organization will create a database that collects submission data; one feature of the database is producing a leaderboard.

Proposed text:
14. Submissions
The MLPerf organization will create a database that collects submission data; one feature of the database is showing a list of systems and their performances with certain system scale filters. E.g. number of instances.

**Comment by bitfort** [comment]
SWG:

We agree to remove the word leaderboard and adjust the text minus the example.
