### ISSUE TITLE
Batch wrapping at epoch boundries

### ISSUE THREAD

**Issue by petermattson** [mlcommons/training_policies#93]
Training set size is not always evenly divisible at batch boundries. One nice way to handle this issue is to "wrap" the batches -- mix samples from end of last epoch with samples from start of next epoch. This makes "every epoch" eval timing tricky. As long as we eval after the wrapped batch it is strictly worse from a work perspective. Is this acceptable?

**Comment by bitfort** [comment]
SWG:

Rationale: this is doesn't improve your score and is not materially relevant. In addition, we think this is a common practice. You can wrap as described above, but this practice should be documented through the logging. To clarify, this should only occur for the last batch of an epoch.

**Comment by codyaustun** [comment]
I am not sure if this is widely used, but PyTorch has an option to drop the last batch if it is incomplete in their [DataLoader](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader) class. Just to be clear, is drop_last=True allowed?

**Comment by petermattson** [comment]
I'd assume this isn't legal because it reduces work. Starting the next
epoch is the same work. Thoughts?

**Comment by codyaustun** [comment]
I agree. I don't think it should be legal. The rules don't seem explicit about this, so it would be good to add a note.
