### ISSUE TITLE
Allow Adam implementations to assume that epsilon is zero in some places.

### ISSUE THREAD

**Issue by robieta** [mlcommons/training_policies#95]
One of our performance experts has requested the ability to treat epsilon as zero in certain places to better accommodate hardware. Given that epsilon is simply a numerical stability factor and in the "ideal mathematical" case it would be arbitrarily small I would propose that allowing this still conforms to the standard of mathematically equivalent to the reference modulo precision constraints.

**Comment by bitfort** [comment]
Context:
Adam optimizers have an epsilon which is basically zero (e.g. 1e-8) which provides numeric stability. There are optimizations which can be made where the epsilon is computed to allow for hardware. 

SWG:
- We generally agree that some flexibility should be allowed here, but we want to make sure it bounded. To this end, a short document will be sent out summarizing the specific optimizations being referred to here. We intend to handle this particular inquiry offline with that document. The particular allowances will be written into the rules. 
- We strongly encourage anyone with similar optimizations to come forward ahead of submission with such optimizations.

**Comment by robieta** [comment]
I followed up with our performance experts, and the specific change that they would like to use is to replace
`sqrt(vt) + epsilon` with `sqrt(vt + epsilon ** 2)` in the denominator of the last update. To justify this change, we present the following perturbation theory:

k is the scale disparity
`epsilon = vt / k`    

```
rel_error = 1 - sqrt(vt + vt**2 / k**2 )
                -------------------------
                   (sqrt(vt) + vt / k)
```

Factor out an vt and divide through

```
rel_error = 1 - sqrt(1 + vt / k**2 )
                -----------------------
                  (1 + sqrt(vt) / k)
```

`eta = vt ** 0.5 / k`

`rel_error = 1 - sqrt(1 + eta**2) / sqrt(1 + eta)`

This function behaves linearly if eta is < ~0.75, and is maximal at eta=1 with a value of 1 - 1/sqrt(2) ~= 0.3. Dropping back out out of eta space:

`eta = x ** 0.5 / (vt / epsilon) = epsilon /sqrt(vt)`

So even at vt == epsilon which is an extreme case, the relative error is still modest (~1e-4)

**Comment by bitfort** [comment]
SWG:

Tentatively agreed unless objections are raised over email by tomorrow.
